TERMUX_PKG_DESCRIPTION="Oil-runtime-compiler"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_VERSION=0.4.32
TERMUX_PKG_SRCURL=https://github.com/GStreamer/orc.git
TERMUX_PKG_GIT_BRANCH=$TERMUX_PKG_VERSION
