TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_VERSION=3.40.2
TERMUX_PKG_SRCURL=https://github.com/GNOME/evolution-data-server.git
TERMUX_PKG_GIT_BRANCH=$TERMUX_PKG_VERSION
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+="-DWITH_KRB5=OFF -DWITH_OPENLDAP=OFF"
TERMUX_PKG_DEPENDS="nspr"
