TERMUX_PKG_DESCRIPTION="Weston compositor for wayland"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_VERSION=9.0.0
TERMUX_PKG_SRCURL=https://github.com/wayland-project/weston.git
TERMUX_PKG_GIT_BRANCH=$TERMUX_PKG_VERSION
